### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by poingg** [estevesnp/dsb#1]
There's no handling of division by 0 at the interpreter level.

```
>>  let x=1/0
panic: runtime error: integer divide by zero

goroutine 1 [running]:
github.com/estevesnp/dsb/pkg/evaluator.evalIntegerInfixExpression({0x1400000e12c, 0x1}, {0x104866a30?, 0x14000110068?}, {0x104866a30, 0x14000110048})
	/Users/eep/Work/dsb/pkg/evaluator/evaluator.go:366 +0x418
github.com/estevesnp/dsb/pkg/evaluator.evalInfixExpression({0x1400000e12c, 0x1}, {0x104866a30, 0x14000110068}, {0x104866a30, 0x14000110048})
	/Users/eep/Work/dsb/pkg/evaluator/evaluator.go:338 +0xdc
github.com/estevesnp/dsb/pkg/evaluator.Eval({0x104866df0?, 0x1400007a050}, 0x14000112020)
	/Users/eep/Work/dsb/pkg/evaluator/evaluator.go:112 +0x7b0
github.com/estevesnp/dsb/pkg/evaluator.Eval({0x104866d78?, 0x1400002c140}, 0x14000112020)
	/Users/eep/Work/dsb/pkg/evaluator/evaluator.go:50 +0x934
github.com/estevesnp/dsb/pkg/evaluator.evalProgram({0x14000010770?, 0x1049a4108?, 0x10?}, 0x14000112020)
	/Users/eep/Work/dsb/pkg/evaluator/evaluator.go:152 +0x98
github.com/estevesnp/dsb/pkg/evaluator.Eval({0x1048669e0?, 0x1400000c060}, 0x14000112020)
	/Users/eep/Work/dsb/pkg/evaluator/evaluator.go:34 +0xbc
github.com/estevesnp/dsb/pkg/repl.Start({0x1048667b8?, 0x14000114010?}, {0x104866798, 0x14000114018})
	/Users/eep/Work/dsb/pkg/repl/repl.go:38 +0x1ac
main.startREPL()
	/Users/eep/Work/dsb/main.go:30 +0x74
main.main()
	/Users/eep/Work/dsb/main.go:19 +0x7c
```

**Comment by estevesnp** [comment]
fixed, thanks for the contribution
